version: 2

jobs:
  install-ugrade-server:
    working_directory: ~/ugrade/server
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/ugrade
          paths:
            - server/node_modules
  
  test-ugrade-server:
    working_directory: ~/ugrade/server
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - attach_workspace:
          at: ~/ugrade/server
      - run:
          name: test
          command: yarn test

  install-ugrade-web:
    working_directory: ~/ugrade/web
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/ugrade
          paths:
            - web/node_modules

  test-ugrade-web:
    working_directory: ~/ugrade/web
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - attach_workspace:
          at: ~/ugrade/web
      - run:
          name: test
          command: yarn test 

  build-ugrade-web:
    working_directory: ~/ugrade/web
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - attach_workspace:
          at: ~/ugrade/web
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: ~/ugrade
          paths:
            - web/build

workflows:
  version: 2
  ugrade:
    jobs:
      - intall-ugrade-server
      - test-ugrade-server:
          requires:
            - install-ugrade-server
      - build-ugrade-web
      - test-ugrade-web:
          requires:
            - build-ugrade-web
      - deliver-ugrade-web:
          requires:
            - build-ugrade-web
            - test-ugrade-web