version: 2
jobs:
  build-ugrade-server:
    working_directory: ~/ugrade/server
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
          path: ~/ugrade
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test-ugrade-server:
    working_directory: ~/ugrade/server
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
          path: ~/ugrade
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  ugrade-server:
    jobs:
      - build-ugrade-server
      - test-ugrade-server:
          requires:
            - build-ugrade-server